//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDS_DataItemDetail
    {
        public int Id { get; set; }
        public int DataItemId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemValue { get; set; }
        public string QuickQuery { get; set; }
        public string SimpleSpelling { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Description { get; set; }
        public int EnabledMark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public string ByName { get; set; }
    }
}
