//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoEntities : DbContext
    {
        public DemoEntities()
            : base("name=DemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lang> Lang { get; set; }
        public virtual DbSet<Menu01> Menu01 { get; set; }
        public virtual DbSet<Menu02> Menu02 { get; set; }
        public virtual DbSet<LoginIP> LoginIP { get; set; }
        public virtual DbSet<DataItem> DataItem { get; set; }
        public virtual DbSet<DataType> DataType { get; set; }
        public virtual DbSet<S_ChatMsg> S_ChatMsg { get; set; }
        public virtual DbSet<S_Room> S_Room { get; set; }
        public virtual DbSet<S_RoomMember> S_RoomMember { get; set; }
        public virtual DbSet<S_User> S_User { get; set; }
    }
}
