//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSQ_NewsWords
    {
        public int id { get; set; }
        public int NewId { get; set; }
        public int WordsId { get; set; }
        public Nullable<int> WordsNum { get; set; }
    }
}
