//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSQ_Log
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public Nullable<int> OperateUserId { get; set; }
        public string OperateManagerId { get; set; }
        public Nullable<int> OperateTypeDetailId { get; set; }
        public string AccessPage { get; set; }
        public string AccessName { get; set; }
        public string IPAddress { get; set; }
        public string Browser { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
