//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSQ_Navigation
    {
        public int Id { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public Nullable<int> Class_Layer { get; set; }
        public Nullable<int> Channel_Id { get; set; }
        public string Nav_Type { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Sub_Title { get; set; }
        public string Icon_Url { get; set; }
        public string Link_Url { get; set; }
        public Nullable<int> Sort_Id { get; set; }
        public Nullable<byte> Is_Lock { get; set; }
        public string Remark { get; set; }
        public string Action_Type { get; set; }
        public Nullable<int> Is_Sys { get; set; }
    }
}
