//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSQ_Web
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string name { get; set; }
        public string Reglx { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string ReglxTitle { get; set; }
        public string ReglxAuthor { get; set; }
        public string ReglxContent { get; set; }
        public string ReglxDate { get; set; }
        public string ReglxImageUrl { get; set; }
    }
}
