//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSQ_Manager_Role_Value
    {
        public int Id { get; set; }
        public int Role_Id { get; set; }
        public string Nav_Name { get; set; }
        public string Action_Type { get; set; }
    }
}
