//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSQ_News
    {
        public int Id { get; set; }
        public int NewTypeDetailId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string title { get; set; }
        public string Images { get; set; }
        public string author { get; set; }
        public string url { get; set; }
        public string sourcewebsite { get; set; }
        public Nullable<int> num { get; set; }
        public string HtmlContent { get; set; }
        public string BodyText { get; set; }
    }
}
