//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSQ_Users
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public string Telephone { get; set; }
        public string UserPassword { get; set; }
        public string SecretKey { get; set; }
        public int EnabledMark { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
    }
}
